# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 04:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_type', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('info', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.TextField()),
                ('social_fb', models.CharField(max_length=200)),
                ('social_twitter', models.CharField(max_length=200)),
                ('social_website', models.URLField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('fb_mentions', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NegocioImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocio', to='spv.Negocio')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.SmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='spv.Negocio')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_name', models.CharField(max_length=50)),
                ('cost', models.SmallIntegerField()),
                ('top', models.BooleanField()),
                ('slider', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.AddField(
            model_name='negocio',
            name='cel1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cel1', to='spv.PhoneModel'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='cel2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cel2', to='spv.PhoneModel'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='cel3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cel3', to='spv.PhoneModel'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry', to='spv.Industry'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='spv.Owner'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='spv.Package'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
