# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='slogan',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
