# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spv', '0004_auto_20160322_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='cel1',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='cel2',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='cel3',
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='local', to='spv.Negocio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='negocio',
            name='fb_mentions',
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
