# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spv', '0005_auto_20160323_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='location',
            field=models.TextField(),
        ),
    ]
