# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spv', '0006_auto_20160323_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodel',
            name='local',
        ),
        migrations.AddField(
            model_name='negocio',
            name='cel1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='cel2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='cel3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='PhoneModel',
        ),
    ]
