# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spv', '0008_auto_20160323_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
