# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spv', '0011_auto_20160327_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocioimg',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spv.Negocio'),
        ),
    ]
