# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spv', '0012_auto_20160327_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='ranking',
            field=models.FloatField(default=0),
        ),
    ]
