# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import spv.models


class Migration(migrations.Migration):

    dependencies = [
        ('spv', '0014_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=spv.models.EventoImg.generate_file_path)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='spv.Evento')),
            ],
        ),
    ]
