# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spv', '0015_eventoimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='decription',
            new_name='description',
        ),
    ]
