# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spv', '0017_auto_20160327_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='location',
        ),
        migrations.AddField(
            model_name='negocio',
            name='latitud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='negocio',
            name='longitud',
            field=models.FloatField(default=0),
        ),
    ]
