# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spv', '0018_auto_20160328_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='direccion',
            field=models.TextField(default='Calle Manuel Doblado 36, Calle Manuel Doblado, Zona Centro, 38800 Moroleón, Gto.'),
            preserve_default=False,
        ),
    ]
