# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spv', '0019_negocio_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
    ]
